import { NextRequest, NextResponse } from 'next/server'
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, PageBreak, Header, Footer, PageNumber,
  BorderStyle, HorizontalPositionAlign, VerticalPositionAlign,
} from 'docx'

function buildDocx(content: string, title: string, meta: Record<string,any> = {}): Promise<Buffer> {
  const { author = 'GhostWrite', style = 'academic', algo = 'std' } = meta
  const algoLabel = algo === 'hyp' ? 'Hyper ⚡' : algo === 'pro' ? 'Pro' : 'Standard'

  // Split content into paragraphs
  const rawParas = content.split(/\n\n+/).filter(p => p.trim().length > 0)

  const bodyChildren: Paragraph[] = rawParas.map(para => {
    const trimmed = para.trim()
    // Detect headings (lines ending with no period, short, possibly numbered)
    const isHeading = trimmed.length < 80 && !trimmed.endsWith('.') && !trimmed.endsWith(',')
      && (trimmed.match(/^\d+\./) || trimmed.match(/^[A-Z][A-Z\s]+$/) || trimmed.split(' ').length <= 6)

    if (isHeading) {
      return new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: trimmed, font:'Calibri', size:28, bold:true, color:'2E2E2E' })],
        spacing: { before:300, after:120 },
      })
    }
    return new Paragraph({
      children: [new TextRun({ text: trimmed, font:'Calibri', size:24, color:'2E2E2E' })],
      alignment: AlignmentType.JUSTIFIED,
      spacing: { after:160, line:276 },
    })
  })

  const doc = new Document({
    creator:     'GhostWrite',
    title,
    description: `Humanized with GhostWrite ${algoLabel} algorithm`,
    sections: [{
      properties: {
        page: {
          margin: { top:1440, right:1440, bottom:1440, left:1440 }
        }
      },
      headers: {
        default: new Header({
          children: [
            new Paragraph({
              children: [
                new TextRun({ text:'GhostWrite', font:'Calibri', size:16, bold:true, color:'7C5CFC' }),
                new TextRun({ text:`  |  ${title.slice(0,60)}`, font:'Calibri', size:16, color:'888888' }),
              ],
              border: { bottom:{ style:BorderStyle.SINGLE, size:4, color:'7C5CFC', space:4 } },
            })
          ]
        })
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              children: [
                new TextRun({ text:'Generated by GhostWrite  —  Invisible craft. Visible results.  —  ', font:'Calibri', size:16, color:'888888' }),
                new TextRun({ children:[PageNumber.CURRENT], font:'Calibri', size:16, color:'888888' }),
                new TextRun({ text:' / ', font:'Calibri', size:16, color:'888888' }),
                new TextRun({ children:[PageNumber.TOTAL_PAGES], font:'Calibri', size:16, color:'888888' }),
              ],
              alignment: AlignmentType.RIGHT,
              border: { top:{ style:BorderStyle.SINGLE, size:4, color:'7C5CFC', space:4 } },
            })
          ]
        })
      },
      children: [
        // Title
        new Paragraph({
          children: [new TextRun({ text: title, font:'Calibri', size:36, bold:true, color:'1A1A2E' })],
          spacing: { after:200, before:120 },
        }),
        // Meta line
        new Paragraph({
          children: [
            new TextRun({ text:`Algorithm: GhostWrite ${algoLabel}  |  Style: ${style}  |  `, font:'Calibri', size:18, color:'888888', italics:true }),
            new TextRun({ text:new Date().toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}), font:'Calibri', size:18, color:'888888', italics:true }),
          ],
          spacing: { after:360 },
          border: { bottom:{ style:BorderStyle.SINGLE, size:4, color:'EEEEEE', space:6 } },
        }),
        ...bodyChildren,
      ]
    }]
  })

  return Packer.toBuffer(doc)
}

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => null)
  if (!body?.content?.trim()) {
    return NextResponse.json({ error:'No content provided.' }, { status:400 })
  }

  const {
    content,
    title   = 'GhostWrite Document',
    format  = 'docx',
    meta    = {},
  } = body

  if (format === 'docx') {
    try {
      const buffer = await buildDocx(content, title, meta)
      const safeName = title.replace(/[^a-z0-9]/gi,'_').slice(0,40).toLowerCase()
      return new NextResponse(buffer, {
        headers: {
          'Content-Type':        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'Content-Disposition': `attachment; filename="${safeName}.docx"`,
          'Content-Length':      String(buffer.length),
        },
      })
    } catch(e: any) {
      return NextResponse.json({ error:`DOCX generation failed: ${e.message}` }, { status:500 })
    }
  }

  // PDF: return structured content for client-side jsPDF rendering
  if (format === 'pdf-data') {
    return NextResponse.json({
      title,
      paragraphs: content.split(/\n\n+/).filter((p:string) => p.trim().length > 0),
      meta,
      date: new Date().toLocaleDateString('en-GB',{ day:'numeric', month:'long', year:'numeric' }),
    })
  }

  return NextResponse.json({ error:`Unsupported format: ${format}` }, { status:400 })
}
